name: my_recipe_book
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.1+96

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  image_picker: ^0.6.2+3 # Apache 2.0
  path_provider: ^1.6.24 # BSD
  image: ^2.1.4 # Apache 2.0
  transparent_image: ^1.0.0 # MIT
  photo_view: ^0.10.3 # MIT
  flutter_image_compress: ^0.6.7 # MIT
  shared_preferences: ^0.5.12+4 # BSD
  archive: ^2.0.13 # Apache 2.0
  file_picker: ^2.1.5 # MIT
  share_extend: ^1.1.9 # MIT
  bottom_navy_bar: ^5.6.0 # Apache 2.0
  intro_slider: ^2.3.3 # MIT
  autocomplete_textfield: ^1.7.3 # MIT
  hive: ^1.4.4+1 # Apache 2.0
  build_runner: ^1.7.1 # BSD
  flutter_bloc: ^6.0.1 # MIT
  equatable: ^1.2.5 # MIT
  flutter_launcher_icons: ^0.8.1 # MIT
  like_button: ^0.2.0 # MIT
  flutter_staggered_grid_view: ^0.3.0 # MIT
  flutter_staggered_animations: ^0.1.2 # MIT
  material_design_icons_flutter: ^4.0.5855 # MIT
  flushbar: ^1.10.2 # Apache 2.0
  flutter_spinkit: ^4.1.1+1 # MIT
  percent_indicator: ^2.1.1+1 # BSD
  draggable_scrollbar: ^0.0.4 # MIT
  share: ^0.6.5+4 # BSD
  gradient_app_bar: ^0.1.3 # BSD
  flutter_sticky_header: ^0.4.2 # MIT
  url_launcher: ^5.7.10 # BSD
  pull_to_refresh: ^1.5.7 # MIT
  showcaseview: ^0.1.5 # BSD
  firebase_admob: ^0.10.3 # BSD
  in_app_purchase: ^0.3.5+1 # BSD
  video_player: ^0.10.10 # BSD
  permission_handler: ^4.4.0 # MIT
  flutter_sequence_animation: ^3.0.1 # MIT
  flutter_native_splash: ^0.1.9 # MIT
  flutter_colorpicker: ^0.3.2 # MIT
  dio: ^3.0.10 # MIT
  hyphenator: ^0.0.3 # BSD
  wakelock: ^0.1.4+1 # BSD
  pdf: ^1.13.0 # Apache 2.0
  printing: ^3.7.2 # Apache 2.0
  buy_me_a_coffee_widget: ^1.0.0 # MIT
  rate_my_app: ^0.6.0+2 # MIT
  # google_fonts: ^1.0.0 # Apache 2.0
  animated_text_kit: ^2.0.1 # MIT
  page_transition: ^1.1.5 # BSD
  circular_check_box: ^1.0.4 # BSD
  reorderables: ^0.3.2 # MIT
  table_calendar: ^2.3.3
  flutter_datetime_picker: ^1.4.0 # MIT

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "ff6f00"

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/iconIos.png"
  image_path_android: "assets/launcher/adaptiveForeground.png"
  adaptive_icon_background: "assets/launcher/adaptiveBackground.png"
  adaptive_icon_foreground: "assets/launcher/adaptiveForeground.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/tomato.png
    - images/milk.png
    - images/meat.png
    - images/randomFood.jpg
    - images/rightArrow.png
    - images/cookingHat.png
    - images/lock.png
    - images/letter.png
    - images/cuisine.jpg
    - images/export.png
    - images/bag.png
    - images/shield.png
    - images/cards.png
    - images/theme.png
    - images/icon.png
    - images/bannerAd.png
    - images/tableVegetable.jpg
    - images/ingredient_search.mp4
    - images/salatLowRes.jpg
    - assets/firstStartRecipes.zip
    - images/foodBlur0.jpg
    - images/foodBlur1.jpg
    - images/foodBlur2.jpg
    - images/foodBlur3.jpg
    - images/iconIosStyle.png
    - images/finishFlag.png
    - images/tabletIngredientSearch.png
    - images/hearts.png
    - images/vegetables.png
    - images/vegetablesBright.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Questrial
      fonts:
        - asset: fonts/Questrial-Regular.ttf
    - family: Ribeye
      fonts:
        - asset: fonts/Ribeye-Regular.ttf
    - family: RibeyeMarrow
      fonts:
        - asset: fonts/RibeyeMarrow-Regular.ttf
    - family: Orbitron
      fonts:
        - asset: fonts/Orbitron-Regular.ttf
    - family: Rancho
      fonts:
        - asset: fonts/Rancho-Regular.ttf
    - family: Righteous
      fonts:
        - asset: fonts/Righteous-Regular.ttf
    - family: Quando
      fonts:
        - asset: fonts/Quando-Regular.ttf
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Bold.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
